version: "3.8"
name: playlive-dev

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3333:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: playlive
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-data:/var/lib/mysql
  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
