spring:
  application:
    name: playLive
  datasource:
    url: jdbc:postgresql://localhost:5432/playlive
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8888

jwt:
  secret: thisIsSecretKeyForTokenPleaseChangeItWhenYouDeploy