spring:
  application:
    name: playLive
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
server:
  port: 8888

jwt:
  secret: thisIsSecretKeyForTokenPleaseChangeItWhenYouDeploy
