spring:
  application:
    name: playLive
  datasource:
    url: jdbc:mysql://localhost:3333/playlive?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8888

jwt:
  secret: thisIsSecretKeyForTokenPleaseChangeItWhenYouDeploy
