spring:
  application:
    name: playLive
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
server:
  port: 8888

jwt:
  secret: thisIsSecretKeyForTokenPleaseChangeItWhenYouDeploy
hls:
  base-path: /home/ubuntu
  video: /home/ubuntu/video
  radio: /home/ubuntu/radio
  thumbnail: /home/ubuntu/thumbnail
