name : build Artifact

run-name: ${{ github.actor }} is start build Actions 🚀

on:
  push:
    branches: ['main']
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: clean test build

      - name: Create SSH Key
        run: | 
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/private-key.pem
          chmod 600 ~/private-key.pem
      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
      - name: Add known host
        run: |
          ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files to remote server
        run: |
          cd ${{ github.workspace }}
          scp -i ~/private-key.pem -r ./build/libs/playLive-0.0.1.jar ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}
          echo "Copied files to remote server"